### ISSUE TITLE
Unable to take screenshot of videos on Surface-view (Videos are from OpenTok).

### ISSUE THREAD

**Issue by veenu123** [opentok/opentok-android-sdk-samples#108]
Hi All,
I am developing an application in Android Studio, where in am doing video calls (Publisher and Subscriber) , taking Screenshots and saving. 
The problem is that when I try to take a screenshot (From a image button) of videos which are playing from 'OpenToK'  will be in black , Not getting the real image.

I am using 'Surface-view' to achieve it , Plz help me to find solution.

**Comment by robjperez** [comment]
`GLSurfaceView` is renderer behind of the rest of the Views of Android. Depending on how you are taking the screenshot, the contents of the SurfaceView won't appear on it.

You have several solutions:
* Build your own custom renderer (See sample `2.Custom-Video-Driver`) and call `readPixels` on the SurfaceView where the publisher/subscribers are being rendered
* Configure OpenTok SDK to use TextureViews instead of SurfaceViews. TextureViews behave like a normal view so you should not have problems capturing the screen.

To do so, you need to pass a [SessionOptions](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html) object when building the OpenTok Session, in that SessionOption you need to override `useTextureViews` to return true.
