### ISSUE TITLE
Publisher video is not visible,when subscriber stream available in Oreo devices 

### ISSUE THREAD

**Issue by techvedikasolutions** [opentok/opentok-android-sdk-samples#164]
Hi,we are using opentok 2.13 sdk,We got an issue in the oreo devices.Publisher video is not displaying whenever subcriber video stream available.Even I checked with the opentok playstore app.In that also same issue is appearing.Can you please help us in solving this issue.Need your assistance in as early as possible(urgent).

Here are the some of the logs(warnings) captured from logcat:

VideoCapabilities: Unrecognized profile 65536 for video/avc
org.webrtc.Logging: MediaCodecVideoEncoder: Found target encoder OMX.qcom.video.encoder.avc. Color: 0x15. Bitrate adjustment: NO_ADJUSTMENT
libc: Access denied finding property "camera.hal1.packagelist"
Camera-JNI: copyAndPost: off=0, size=64 msg=100000
Camera: mCameraStateCallback is null
Camera-JNI: copyAndPost: off=0, size=460800 msg=10

![screenshot_20180215-212436](https://user-images.githubusercontent.com/22232011/36296982-2e40ad26-1316-11e8-8acf-f6b9d2ad4b8e.png)

**Comment by techvedikasolutions** [comment]
I solved this by using  following code
if (mPublisher.getView() instanceof GLSurfaceView) {
            ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true);
        }
For oreo devices we need to add this code to show the publisher video.

**Comment by marinaserranomontes** [comment]
Great!! Thanks for sharing it.

Please note, if you are using GLSurfaceView, which is what OpenTok sdk uses by default, to fix the Z-ordering:
https://github.com/opentok/opentok-android-sdk-samples/blob/master/Basic-Video-Chat/app/src/main/java/com/tokbox/android/tutorials/basic_video_chat/MainActivity.java#L193

Or you could use TextureViews instead of GLSurfaceView
https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html#SessionOptions--

**Comment by priyasamyal** [comment]
Thanks, this works.
