### ISSUE TITLE
onStreamReceived called before session.onResume

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#192]
Hi Team,

I am facing issue of stream received when session is in pause state.
It should be called when session is resumed.
Please look into it.
Thanks
Ashish

**Comment by ashishnagarro** [comment]
Any update on this?

**Comment by msach22** [comment]
@ashishnagarro Apologies for the delay on this. Are you seeing this happen with the BasicVideoChat?  Can you describe what you mean by session is in pause state?

**Comment by ashishnagarro** [comment]
@msach22 : When i have called session.onPause and if someone publish from other device, then i am getting callback in onStreamReceived. But it should not happen until i don't resume session

**Comment by robjperez** [comment]
Hi @ashishnagarro 

Maybe the name is misleading, but `session.onPause` is not "pausing" the opentok session. The name is linked to activity lifecycle method.

When you call `session.onPause` what it's done is to stop streaming video and stop video capturing, but session events like connection ones, or stream received events are still working since the app is actually connected to the session. (it is still transmiting and receiving audio).

If you want to "disconnect" from the session while the app is on the background you can implement that in the app.
