### ISSUE TITLE
Subscriber on pause not working

### ISSUE THREAD

**Issue by TooLazyy** [opentok/opentok-android-sdk-samples#194]
When i minimize my application I call `mSession.onPause()`.
I have only one subscriber which connects to the stream.
But in minimized state I still can hear opentok stream sound, seems to be subscriber don't stop properly.
As I can see - `session.onPause()` refers to subscriber's `onPause` method, which refers to `renderer.pause()` and does not stop audio stream.
```
Android version - 9
Opentok sdk version - 2.15.3
Permissions - MODIFY_AUDIO_SETTINGS, CAMERA, RECORD_AUDIO
```

**Comment by Arunkarthicknallasami** [comment]
Any solutions for this you were able to achieve?

**Comment by TooLazyy** [comment]
> Any solutions for this you were able to achieve?

Yes. Just call `subscriber.setSubscribeToAudio(boolean)` with `false` for **pause** and `true` for **resume**.
But I think that's kind of bug and must be fixed.

**Comment by janoonaj** [comment]
Please note it is the expected behaviour. As refered on docs

> public void onPause()
> 
> Call this method when the app's activity pauses. This pauses the video renderer and capturer of any publishers to the session. It also pauses the video renderers of all subscribers.
> 
> Cameras used by OpenTok publishers are now released when you call this method. Publishers reacquire cameras when you call the onResume() method.


[https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.html#onPause--](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.html#onPause--)

**Comment by msach22** [comment]
As @janoonaj mentioned, this is expected behavior. You can use `setSubscribeToAudio` to toggle the subscriber's audio. Similarly, you can also use `setPublishAudio` and `setPublishVideo` to toggle the publisher's audio and video at the different lifecycles.

This is intentional because it gives the developer granularity. For example, in PIP mode, you may not want to stop subscribing to the subscriber's audio.
