### ISSUE TITLE
Sending a transparent RGBA frame to Remote Device 

### ISSUE THREAD

**Issue by afsaredrisy** [opentok/opentok-android-sdk-samples#199]
I am trying to send ARGB frame that contains ALPHA Channel value but when I am rendering on GLSurfaceview on remote device its background is coming black. ALPHA value is being lost somewhere during I420 encoding. So is there any way to send ARGB frame so that Transparency may preserve. 

Other thing is in Custom video driver you provide shader code that is converting YUV to RGB and setting ALPHA value to 1.0 (i.e opaque)  is there any way to calculate ALPHA value from YUV itself in shader code.?
Thankyou

**Comment by robjperez** [comment]
hi @afsaredrisy 

Actually this is a very interesting question. There is no way of direclty sending an alpha channel using our sdk, since we convert the ARGB frames to YUV in order to encode them and there is no transparency information in YUV as you mentioned.

However, you may be able to use alpha information doing some kind of image processing. 
You could use a background color (typically green) that will be mapped to a specific Chroma Key, and then remove that specific color in the opengl shader. 

You can search for chromakey and yuv.

I'm going to close this since it is not technically an issue nor the samples neither the sdk.
