### ISSUE TITLE
Subscribe video pixelation

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#201]
Hi Team,

I am facing issue of pixelation of stream. could you please tell me some workaround to resolve this issue.

One more thing - could you please let me know how to enable this Simulcast mode?
Thanks in advance.

**Comment by robjperez** [comment]
Quality issues are usually due to different conditions, it is hard to say that the quality degradation is because some particular thing.

I recommend looking into the particular session using our inspector tool: https://tokbox.com/developer/tools/inspector_doc/

There you can see network conditions that might affect to the quality.

Simulcast is enabled by default, you don't need to do anything in particular.

Going to close the ticket but please reopen this or report a new one if you still see quality problems.
