### ISSUE TITLE
Resize Frame Issue

### ISSUE THREAD

**Issue by madhaviKumari** [opentok/opentok-android-sdk-samples#206]
When I am sending a frame of fixed size from CustomVideoCapturer like this from onPreviewFrame()
`provideIntArrayFrame(pixels, ARGB, bitmap_output.getWidth(),
                        bitmap_output.getHeight(), currentRotation, isFrontCamera(), framemetadata);`

Problem is when I am getting this frame in VideoRenderer onFrame() then some time it is coming of exact same size but some time it is automatically reduced to some smaller size. 
My Requirement is to fixed frame size in every situation. Why it reducing size after applying to    provideIntArrayFrame();

**Comment by robjperez** [comment]
Hi @madhaviKumari 

The sdk will adapt the frame size according network conditions or cpu usage in order to keep the video stream working.
If the sdk would send fixed frame sizes, then the network could not be good enough to support the bitrate and video frames will be dropping.

Going to close the issue since this is how the sdk works.
