### ISSUE TITLE
Runtime error OpenTok 2.16.0

### ISSUE THREAD

**Issue by shahalRahman** [opentok/opentok-android-sdk-samples#213]
Application was running fine on Version 2.15.3 but on updating it to version 2.16.0, i'm getting 3 errors
1. Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/username/.gradle/caches/transforms-1/files-1.1/opentok-android-sdk-v3-3.1.0.aar/fcef1a54e1fe1e3f6ef61327afe0a74e/jars/libs/libwebrtc.jar

2. Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/webrtc/SurfaceViewRenderer.class

3. Caused by: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

Below is my Gradle configuration
`android {
  compileSdkVersion 22
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "com.example.samplevideocall"
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    dexOptions {
        javaMaxHeapSize "4g"
        preDexLibraries = false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
`
I'm using Android Studio 3.3.2

**Getting the same issue on OpenTok Sample Basic-Video-Chat.**

**Comment by robjperez** [comment]
From 2.16 onwards, it is required to add Java8 language support to your project, please add this to your build.gradle file 
```
android {
...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
...
}```

**Comment by PonyHugger** [comment]
Is there a way to use the current OpenTok SDK on devices with an Android SDK API level lower than 24?
Due to the use of Java 8, i am not able to compile on an Android 5.1 device (API level 22).

"The OpenTok Android SDK works with any Android 4.1+ device (Jelly Bean, API Level 16) that has a camera (for publishing video) and adequate CPU and memory support." ... seems to be wrong...

source. https://tokbox.com/developer/sdks/android/#requirements

**Comment by robjperez** [comment]
Hi @PonyHugger 

There are two levels when developing android applications.
`targetSdkVersion` is the sdk you use to build the application. It is a best practice to use the latest one.
`minSdkVersion` is the mininum supported version

You should be fine setting targetSdkVersion to 26 and minSdkVersion to 16

You can read more about this here: https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

**Comment by PonyHugger** [comment]
Hi @robjperez 

thanks for your reply! In order for me to be able to support Java 8 and have a API version less than 24, I am forced to enable jackOptions in my build.gradle. This leads to a Jack compilation exception saying `Default method long createNativeVideoDecoder() not supported in Android API level less than 24`.

As I am currently not able to upgrade my Android plugin to 3.0.0 or higher due to compatibility reasons with other modules, I am not able to use the bytecode transformation called „desugar“ (https://developer.android.com/studio/write/java8-support). Anyways this wouldn’t get rid of the fact, that the method call createNativeVideoDecoder() is only supported for API levels less than 24, right?

**Comment by robjperez** [comment]
Hi again,

Unfortunatelly we don't support jack usage (as it is already deprecated). Our library has Java8 bytecode so you will need to use last java 8 support.

When using targetSdkVersion 26 (or 28) that error should go away.

**Comment by PonyHugger** [comment]
Hi @robjperez ,
thank you very much! We are facing a new problem:
#232 
Cheers!
