### ISSUE TITLE
onStreamReceived not calling some times.

### ISSUE THREAD

**Issue by rsekharAppyog** [opentok/opentok-android-sdk-samples#224]
Hi, 
Some times onStreamReceived is not calling for the person who initiated the call.

As per the discussion in this thread - https://github.com/opentok/opentok-android-sdk-samples/issues/132, onStreamReceived will only call only if there is new subscriber added into the session. 

So what will happen if the person (Person A) initiating the call who got delay to connect the session but the other person (Person B) connected to the session earlier. In this case, Person B will receive the onStreamReceived method but Person A won't receive.

Is it my understanding right? 

If yes how can we solve this and also is it possible to get all stream (subscriber's) from the session?
If no then why it is not triggering?

**Comment by robjperez** [comment]
@rsekharAppyog In the case you are describing, Person A should receive `onStreamReceived`, so that he or she knows that another person in in the session.

Please let us know if that is not the case.

I'll be closing the ticket, please reopen it if you find the callback is not being called in the latest version of the sdk
