### ISSUE TITLE
Publisher resolution impact

### ISSUE THREAD

**Issue by janoonaj** [opentok/opentok-android-sdk-samples#264]
Hello,

Using CustomPublisher example, I am trying to understand what is the Publisher resolution impact if camera settings are different than Publisher settings.

For example, what happens if we set
- `Publisher: Publisher.CameraCaptureResolution.HIGH`
but in camera parameters we configure
```
//-- function startCapture() code -------
 Camera.Parameters parameters = mCamera.getParameters();
        parameters.setPreviewSize(320, 240);
//------------------
//------------------
//------------------

@Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        mPreviewBufferLock.lock();
        if (isCaptureRunning) {
            if (data.length == mExpectedFrameSize) {
                // Get the rotation of the camera
                int currentRotation = compensateCameraRotation(mCurrentDisplay
                        .getRotation());

                // Send frame to OpenTok
                provideByteArrayFrame(data, NV21, 320, 240, currentRotation, isFrontCamera());

                // Reuse the video buffer
                camera.addCallbackBuffer(data);
            }
        }
        mPreviewBufferLock.unlock();
    }
```

For example, what happens if we setup a 1024p video resolution from the camera settings when tokbox only accepts 720p?

We have seen some crashes if we setup 1024p on a OTG camera with ublisher.CameraCaptureResolution.LOW (or medium), but don't know if it is related.

Same questions with FPS. It is hard to understand what does FPS tokbox publisher/subscriber params if we manually setup a lower or higher number on camera params.

Thanks a lot

**Comment by robjperez** [comment]
tokbox only supports up to 720p video streaming, however what you feed to the sdk in terms of resolution and frame rate is not always what we stream.

The sdk will adapt to network and cpu conditions so that it will send the best resolution and fps given those constraints.

Let's say you capture in 720p/30fps and you feed with those frames to the sdk, if you are in a bad network, we will downscale the frames to 640x480 or even 320x240 with 10 or 15fps if necessary.

Also, that the sdk is not doing is upscaling the frames, if you capture at 320x240, sdk won't never send above that.

Hope this help with your question.

I'm going to close this since it does not look like an issue with the samples or the sdk, but please don't hesitate to continue the conversation here.
