### ISSUE TITLE
How to use a custom AAC byte[] (stream) as a source for input inside a CustomAudioDevice

### ISSUE THREAD

**Issue by acrolink** [opentok/opentok-android-sdk-samples#265]
I am using the following library to connect a Logitech C270 camera to an Android 8.0 Smart TV. 
[AndroidUSBCamera](https://github.com/jiangdongguo/AndroidUSBCamera)

I have managed to capture the image and stream it to the second peer. However, I am having a trouble with the audio from the webcam. I have the AAC stream as a `byte[]`. I want using the `CustomAudioDevice` example to use it as an input so it would be streamed the other video chat peer.

My question, how to do that? Thank you very much.

**Comment by robjperez** [comment]
The custom audio device takes *unencoded* samples, if you have AAC samples, it won't work with the Custom Audio Device since those samples are already encoded.

You would need to fetch samples in raw PCM format.

I'm going to close the ticket since this is not an issue, but please continue the discussion in here if needed
