### ISSUE TITLE
Mirror effect while using front camera

### ISSUE THREAD

**Issue by sagar-nickelfox** [opentok/opentok-android-sdk-samples#284]
While using front camera the video flips on viewer end. We do not have control over it.

Do we have some kind of check to not to use mirror camera effect?

**Comment by robjperez** [comment]
Thanks for commenting @sagar-nickelfox 

Actually there isn't a way of changing this in the SDK, however the image which is mirrored is the local render, but the remote view is not changed from what the camera captures.

We mirror the local render because it feels strange not to mirror the image when you are looking at yourself.

In any case, there is a way to do that and it is creating a custom video capturer, take a look to this sample: https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Capturer-Camera2

In the capturer you can flip the image coming from the camera and before sending it to the other end.

I'm going to close the ticket since it is not an issue of the sdk, we can continue with the discussing in this issue.
