### ISSUE TITLE
How to do screenshare of entire android (like zoom)

### ISSUE THREAD

**Issue by nagendraK6** [opentok/opentok-android-sdk-samples#285]
I read the screenshare sample code. Looks like it is trying to share android webview. I am looking for the functionality like zoom screen sharing, where user can share entire screen. Can anyone help me on this?

**Comment by robjperez** [comment]
In the sample we are using `View.draw(canvas)` to dump the contents of a given view into a bmp canvas, and then send that canvas to the SDK to be streamed.

If you want to capture the whole screen you have two options depending on your use case:

1. Use a root view of your application as the view used by the `View.draw` method. You can use the ScreensharingCapturer of the sample but passing to the constructor a root view of your application (instead of a child view like the sample does)

2. Use [MediaProjection API](https://developer.android.com/reference/android/media/projection/MediaProjection) to get the contents of the screen and fetch RGB data from the surface and then send it to the SDK.

I'm going to close the issue since it is not strictly an issue of the samples, but please post here any comment you might have.
