### ISSUE TITLE
OpenTok publisher is unable to send stream video in background mode

### ISSUE THREAD

**Issue by palmas** [opentok/opentok-android-sdk-samples#286]
There is a problem with openTok on Android. If app goes to background mode and stays in background for approximately 1 minute, publisher's view becomes black and publisher is unable to send stream video at subscriber side.

No errors in logs, publisher’s onError and onStreamDestroyed callbacks are not triggered as well.

OpenTok sdk version: 2.16.5, Android version: 9.0

The issue is reproduced on device with android version 9.0 but not reproduced on device with 7.1.2 version.

**Comment by robjperez** [comment]
Thanks for reporting @palmas 

By default when the activity is onPause the video capturing and sending is paused.
Once the activity is resumed the video should resume also.

This happens if you call `session.onPause()` `session.onResume()` in your activity corresponding methods.

**Comment by palmas** [comment]
Thank you for reply, @robjperez. 
But in our app we do not call session.onPause() session.onResume() methods. So it is expected that publisher will continue stream video. 

I also checked Basic-Video-Chat with removed mSession.onPause() and mSession.onResume() lines and the mentioned scenario reproduced as well

**Comment by robjperez** [comment]
Hi @palmas 

Capturing video while the activity is on the background is actually forbidden by Android SDK itself. Look: https://developer.android.com/guide/topics/media/camera#considerations

Actually it works for some time, and probably it behaves different depending on the Android SDK or the device, however Android will disconnect the capturing at any time, so you should not do it.

The solution will be probably implementing a Custom Capturer that uses a foreground service that will keep the capture session opened.

I'm going to close the issue since it does not look like an issue of the SDK but an expected way of working.
