### ISSUE TITLE
SubscriberKit.SubscriberListener.onDisconnected not being called in 2.17.1

### ISSUE THREAD

**Issue by Fando** [opentok/opentok-android-sdk-samples#294]
**sdk version:** 2.17.1
**tested on device:** pixel 2 with android 10

When calling `session.subscribe(subscriber)`, `SubscriberListener.onConnected` is called, however,

when calling `session.unsubscribe(subscriber)`, `SubscriberListener.onDisconnected` is not called.

Looking at the code of, `SubscriberKit.class`, I see code points which call, `SubscriberListener.onConnected`, `SubscriberListener.onError`, but not `SubscriberListener.onDisconnected`

Is this behaviour intentional? If so, is there another way to listen for stream un-subscription? Should I assume that when I call `session.unsubscribe(subscriber)`, that I'm unsubscribed, without relying on any callbacks?

If the intended behaviour is to never issue a callback for onDisconnected, then it would be helpful to remove this method from the listener interface to avoid confusion.

**Comment by robjperez** [comment]
Hi @Fando 

The `onDisconnected` callback is called when a subscriber leaves the session remotely, so you know when a subscriber is no longer in a session and update the UI accordingly. You don't need to unsubscribe to the subscriber in this case since it is no longer in the session.

When you call `session.unsubscribe(subscriber)` there is no callback involved. You won't be subscribing anymore to it after calling that method. The `onDisconnected` callback does not apply in this case.

Hope it helps.

I'm going to close the ticket since it is not an issue, please reopen if necessary.
