### ISSUE TITLE
Vulnerable WebRTC Version

### ISSUE THREAD

**Issue by dimitar-zabaznoski** [opentok/opentok-android-sdk-samples#444]
On the Android platform, when submitting a version for review on PlayStore we get a warning about a vulnerable WebRTC version:

> Your app uses a bad version of WebRTC, which contains security vulnerabilities.

![webrtc](https://user-images.githubusercontent.com/13835185/211592687-546d663a-cd03-407a-abb5-c8c84532eaa6.png)

The learn more link: https://support.google.com/faqs/answer/12577537 

The latest android Opentok version at the time 2.24.1 seems to use older version of WebRTC 99.2.39 (vs. the latest 108.0.0)

**Comment by v-kpheng** [comment]
Thanks, @dimitar-zabaznoski, for letting us know about this.

This issue was reported by other users as well: https://jira.vonage.com/browse/OPENTOK-49409.

The warning is misleading, though.  The warning is generated using a basic scan of the version of `libwebrtc` being used.  Although we do use that version, we don't use the internal library impacted by the security vulnerability.  As a matter of fact, our platform doesn't even support WebRTC Data Channels, which is the attack vector.  See also https://tokbox.com/developer/sdks/android/release-notes.html

<img width="989" alt="image" src="https://user-images.githubusercontent.com/49660118/213311171-b7bda72e-6362-4212-971f-e69ea1f2ae1f.png">


In any case, we'll update to a newer version, but we don't have an ETA for that.
